/* RiftZay - daily price-history collector
 *
 * Appends today's TCGplayer market price for every priced card to
 * data/price_history.js, so the prediction engine has a real time series
 * to forecast from. Runs nightly via .github/workflows/collect-history.yml
 * (and can be run locally:  node tools/collect_history.js ).
 *
 * Data layout (compact, column-per-date):
 *   window.RIFTZAY_PRICE_HISTORY = {
 *     "dates": ["2026-08-14", ...],              // ascending, YYYY-MM-DD
 *     "series": { "ven-001-166": [0.07, ...] }   // aligned to dates, null = missing
 *   };
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PRICES_FILE = path.join(ROOT, 'data', 'prices.js');
const HISTORY_FILE = path.join(ROOT, 'data', 'price_history.js');

const SETS = [
    { id: 24698, abbr: 'VEN' }, { id: 24560, abbr: 'UNL' }, { id: 24519, abbr: 'SFD' },
    { id: 24552, abbr: 'JDG' }, { id: 24344, abbr: 'OGN' }, { id: 24439, abbr: 'OGS' },
    { id: 24528, abbr: 'OPP' }, { id: 24343, abbr: 'PR' }, { id: 24797, abbr: 'SGN' },
];
const BASE = 'https://tcgtracking.com/tcgapi/v1/89/sets/';
const MAX_DAYS = 120;

function parseGlobal(src, name) {
    const m = src.match(new RegExp('window\\.' + name + '\\s*=\\s*(\\{.*?\\});', 's'));
    if (!m) throw new Error(name + ' not found in ' + PRICES_FILE);
    return JSON.parse(m[1]);
}

function todayStr() {
    return new Date().toISOString().slice(0, 10);
}

async function fetchJson(url) {
    const r = await fetch(url);
    if (!r.ok) throw new Error(url + ' -> HTTP ' + r.status);
    return r.json();
}

async function main() {
    const pricesSrc = fs.readFileSync(PRICES_FILE, 'utf8');
    const productMap = parseGlobal(pricesSrc, 'RIFTZAY_PRODUCT_MAP'); // slug -> productId

    // Fresh market price per productId from the Open TCG API
    const marketByProduct = {};
    for (const s of SETS) {
        const pricing = await fetchJson(BASE + s.id + '/pricing');
        for (const [pid, entry] of Object.entries(pricing.prices || {})) {
            const tcg = entry.tcg || {};
            const n = tcg.Normal, f = tcg.Foil;
            const m = n && n.market != null ? n.market : (f && f.market != null ? f.market : null);
            if (m != null) marketByProduct[pid] = Math.round(m * 100) / 100;
        }
    }
    console.log('products priced today:', Object.keys(marketByProduct).length);

    // slug -> market today
    const today = todayStr();
    const todayPoints = {};
    for (const [slug, pid] of Object.entries(productMap)) {
        if (marketByProduct[pid] != null) todayPoints[slug] = marketByProduct[pid];
    }
    console.log('cards priced today:', Object.keys(todayPoints).length);

    // Load existing history
    let dates = [];
    let series = {};
    if (fs.existsSync(HISTORY_FILE)) {
        try {
            const h = parseGlobal(fs.readFileSync(HISTORY_FILE, 'utf8'), 'RIFTZAY_PRICE_HISTORY');
            dates = h.dates || [];
            series = h.series || {};
        } catch (e) { console.warn('history parse failed, starting fresh:', e.message); }
    }

    // Add/overwrite today's column
    if (dates[dates.length - 1] === today) {
        const idx = dates.length - 1;
        for (const [slug, v] of Object.entries(todayPoints)) series[slug][idx] = v;
    } else {
        dates.push(today);
        const idx = dates.length - 1;
        for (const [slug, v] of Object.entries(todayPoints)) {
            if (!series[slug]) series[slug] = new Array(idx).fill(null);
            series[slug][idx] = v;
        }
    }

    // Prune to MAX_DAYS
    if (dates.length > MAX_DAYS) {
        const drop = dates.length - MAX_DAYS;
        dates = dates.slice(drop);
        for (const slug of Object.keys(series)) series[slug] = series[slug].slice(drop);
    }

    // Round values to 2dp for a smaller file
    for (const slug of Object.keys(series)) {
        series[slug] = series[slug].map(function (v) {
            return v == null ? null : Math.round(v * 100) / 100;
        });
    }

    const out =
        '// Generated by tools/collect_history.js from the Open TCG API (tcgtracking.com).\n' +
        '// Daily market-price snapshots used by the prediction engine. Do not edit by hand.\n' +
        'window.RIFTZAY_PRICE_HISTORY = ' +
        JSON.stringify({ dates: dates, series: series }) + ';\n';

    fs.writeFileSync(HISTORY_FILE, out, 'utf8');
    console.log('wrote', HISTORY_FILE, Buffer.byteLength(out, 'utf8'), 'bytes, days:', dates.length);
}

main().catch(function (e) { console.error(e); process.exit(1); });