/* RiftZay - tournament metagame collector
 *
 * Fetches the competitive card-stats dataset and writes a compact per-card
 * metagame snapshot to data/meta.js. The prediction engine uses this as a
 * leading indicator: cards that show up in winning tournament decks tend to
 * move in price before the TCGplayer market catches up.
 *
 * Source: BoundRift (https://boundrift.com/api/stats/cards) - a community
 * Riftbound tournament database that publishes per-card stats (deck count,
 * play rate, win rate, games) keyed by the exact RiftZay card slug, so we
 * can join directly to the price data. The previous source (riftdecks.com)
 * sits behind Cloudflare bot protection that blocks automated access, so
 * this collector was switched to BoundRift's open JSON API.
 *
 * Runs nightly with the price collector. Can be run locally:
 *   node tools/collect_meta.js
 *
 * Data layout:
 *   window.RIFTZAY_TOURNAMENT_META = {
 *     "updated": "2026-08-17",
 *     "cards": { "ogn-045-298": { "name": "...", "decks": 1015, "copies": 3,
 *       "play": 39, "games": 2346, "win": 50 } }
 *   };
 *   - decks  total tournament decks the card appeared in
 *   - copies average copies per deck
 *   - play   % of tournament decks that ran the card
 *   - games  games recorded with the card
 *   - win    % win rate of decks running the card
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const META_FILE = path.join(ROOT, 'data', 'meta.js');
const CARDS_FILE = path.join(ROOT, 'data', 'cards.js');

const URL = 'https://boundrift.com/api/stats/cards';

function todayStr() {
    return new Date().toISOString().slice(0, 10);
}

async function fetchJson(url) {
    const r = await fetch(url);
    if (!r.ok) throw new Error(url + ' -> HTTP ' + r.status);
    return r.json();
}

/* Card name lookup: the card catalog (data/cards.js) uses cardCode as the
 * slug, exactly the same format BoundRift's cardId uses. */
function loadNames() {
    const names = {};
    try {
        const src = fs.readFileSync(CARDS_FILE, 'utf8');
        const m = src.match(/window\.RIFTZAY_CARDS_BUNDLE\s*=\s*(\[.*?\]);/s);
        if (!m) return names;
        const cards = JSON.parse(m[1]);
        for (const c of cards) {
            if (c && c.cardCode) names[c.cardCode] = c.fullName || c.name;
        }
    } catch (e) {
        console.log('could not read card catalog names:', e.message);
    }
    return names;
}

async function main() {
    console.log('fetching', URL);
    let data;
    try {
        data = await fetchJson(URL);
    } catch (e) {
        // Source unreachable / blocked: keep the last known-good snapshot so
        // we never break the pipeline or ship stale data overwritten by null.
        console.log('Could not reach the tournament source (' + URL + ') - keeping existing data/meta.js');
        console.log('EXIT: skipped (no fresh data)');
        return;
    }

    const rows = data && data.cards;
    if (!rows || !rows.length) {
        console.log('Empty tournament payload - keeping existing data/meta.js');
        console.log('EXIT: skipped (no fresh data)');
        return;
    }
    console.log('rows fetched:', rows.length, '| decks:', data.totalDecks, '| events:', data.eventCount);

    const names = loadNames();
    const cards = {};
    let joined = 0;
    for (const row of rows) {
        const slug = row.cardId;
        if (!slug || !/^(ven|unl|sfd|ogn|ogs|jdg|pr|sgn)-/.test(slug)) continue;
        cards[slug] = {
            name: names[slug] || null,
            decks: row.deckCount != null ? Math.round(row.deckCount) : null,
            copies: row.avgCopies != null ? Math.round(row.avgCopies * 10) / 10 : null,
            play: row.playRatePct != null ? Math.round(row.playRatePct * 10) / 10 : null,
            games: row.games != null ? Math.round(row.games) : null,
            win: row.winRatePct != null ? Math.round(row.winRatePct * 10) / 10 : null,
        };
        joined++;
    }
    console.log('cards with a RiftZay slug:', joined);

    const out =
        '// Generated by tools/collect_meta.js from BoundRift tournament data (boundrift.com).\n' +
        '// Competitive metagame snapshot (decks / play% / win%) per card. Do not edit by hand.\n' +
        'window.RIFTZAY_TOURNAMENT_META = ' +
        JSON.stringify({ updated: todayStr(), cards: cards }) + ';\n';

    fs.writeFileSync(META_FILE, out, 'utf8');
    console.log('wrote', META_FILE, Buffer.byteLength(out, 'utf8'), 'bytes,', joined, 'cards');
}

main().catch(function (e) { console.error(e); process.exit(1); });