/* RiftZay - tournament metagame collector
 *
 * Fetches the competitive card-stats dataset from riftdecks.com (the
 * community-run Riftbound tournament database: ~2000 events, decklists, and
 * standings) and writes a compact per-card metagame snapshot to
 * data/meta.js. The prediction engine uses this as a leading indicator:
 * cards that show up in winning tournament decks tend to move in price
 * before the TCGplayer market catches up.
 *
 * Source: https://riftdecks.com/cards/stats - the page embeds a JSON array
 * (var DATA = [...]) with per-card tournament stats. Each row has an image
 * path like /img/cards/riftbound//OGN/ogn-045-298_cropped.png whose filename
 * (ogn-045-298) is exactly a RiftZay card slug, so we can join directly to
 * the price data.
 *
 * The page sits behind Cloudflare bot protection, so it is fetched with
 * curl (installed on GitHub Actions ubuntu runners and Windows 10+) using a
 * browser User-Agent; Node's default HTTP fingerprint is rejected.
 *
 * IMPORTANT - best effort: if the source is unreachable (e.g. from a
 * datacenter IP that Cloudflare blocks), the existing data/meta.js is left
 * untouched rather than overwritten, so the job never fails and the
 * prediction engine keeps using the last known-good snapshot. Run locally
 * (node tools/collect_meta.js) to refresh whenever the network can reach it.
 *
 * Runs nightly with the price collector. Can be run locally:
 *   node tools/collect_meta.js
 *
 * Data layout:
 *   window.RIFTZAY_TOURNAMENT_META = {
 *     "updated": "2026-08-14",
 *     "cards": { "ogn-045-298": { "name": "...", "decks": 1015, "copies": 3,
 *       "play": 39, "games": 2346, "win": 50 } }
 *   };
 *   - decks  total tournament decks the card appeared in
 *   - copies average copies per deck
 *   - play   % of tournament decks that ran the card
 *   - games  games recorded with the card
 *   - win    % win rate of decks running the card
 */

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const META_FILE = path.join(ROOT, 'data', 'meta.js');

const URL = 'https://riftdecks.com/cards/stats';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

function todayStr() {
    return new Date().toISOString().slice(0, 10);
}

function fetchHtml() {
    // curl with a browser UA (Node's fingerprint is blocked by Cloudflare).
    try {
        return execFileSync('curl', ['-s', '-A', UA, '--max-time', '60', URL], {
            encoding: 'utf8', maxBuffer: 32 * 1024 * 1024, stdio: ['pipe', 'pipe', 'pipe'],
        });
    } catch (e) {
        console.log('curl failed:', (e.message || '').split('\n')[0]);
        return null;
    }
}

function extractData(html) {
    if (!html || html.length < 1000) return null;
    const m = html.match(/var DATA = (\[.*?\]);\s*$/m);
    if (!m) return null;
    try { return JSON.parse(m[1]); }
    catch (e) { console.log('DATA parse error:', e.message.split('\n')[0]); return null; }
}

function main() {
    console.log('fetching', URL, '(via curl)');
    const html = fetchHtml();
    const rows = extractData(html);
    if (!rows) {
        // Source unreachable / blocked: keep the last known-good snapshot so
        // we never break the pipeline or ship stale data overwritten by null.
        console.log('Could not reach the tournament source (' + URL + ') - keeping existing data/meta.js');
        console.log('EXIT: skipped (no fresh data)');
        return;
    }
    console.log('rows fetched:', rows.length);

    const cards = {};
    let joined = 0;
    for (const row of rows) {
        const mm = row.img && row.img.match(/\/(ven|unl|sfd|ogn|ogs|jdg|pr)\/([a-z0-9]+(?:-star)?-\d+-\d+)_/i);
        if (!mm) continue;
        const slug = mm[2].toLowerCase();
        cards[slug] = {
            name: row.name || null,
            decks: row.decks != null ? Math.round(row.decks) : null,
            copies: row.copies != null ? Math.round(row.copies * 10) / 10 : null,
            play: row.play != null ? Math.round(row.play * 10) / 10 : null,
            games: row.games != null ? Math.round(row.games) : null,
            win: row.win != null ? Math.round(row.win * 10) / 10 : null,
        };
        joined++;
    }
    console.log('cards with a RiftZay slug:', joined);

    const out =
        '// Generated by tools/collect_meta.js from riftdecks.com tournament data.\n' +
        '// Competitive metagame snapshot (decks / play% / win%) per card. Do not edit by hand.\n' +
        'window.RIFTZAY_TOURNAMENT_META = ' +
        JSON.stringify({ updated: todayStr(), cards: cards }) + ';\n';

    fs.writeFileSync(META_FILE, out, 'utf8');
    console.log('wrote', META_FILE, Buffer.byteLength(out, 'utf8'), 'bytes,', joined, 'cards');
}

main();